import assert from 'node:assert/strict';
import { app } from '../server';
import { createHash } from 'node:crypto';
import { once } from 'node:events';
import { db, pool, FieldValue } from '../backend/database';
import { mountAuth } from '../backend/auth';
import { mountDataApi } from '../backend/dataApi';
import { mountInventory } from '../backend/inventory';
import { migrateDatabase } from './migrate-database';
const url = new URL(process.env.DATABASE_URL || 'postgresql://localhost/missing');
if (!url.pathname.endsWith('/vine_test') || process.env.ALLOW_TEST_DATABASE !== 'yes') throw new Error('Use an isolated vine_test database and ALLOW_TEST_DATABASE=yes');
await migrateDatabase();
await pool.query('TRUNCATE service_branch_settings, services, service_categories, app_records, auth_sessions, auth_identities, oauth_attempts');
let assertions = 0;
function check(condition: any, message: string) { assert.ok(condition, message); assertions++; }
const counter = db.collection('counters').doc('test');
await counter.set({ count: 0 });
await Promise.all(Array.from({ length: 12 }, () => db.runTransaction(async tx => {
  const data = (await tx.get(counter)).data()!; tx.update(counter, { count: data.count + 1 });
})));
check((await counter.get()).data()?.count === 12, 'Concurrent transactions preserve every increment');
await assert.rejects(db.runTransaction(async tx => { tx.update(counter, { count: 99 }); throw new Error('rollback'); }));
check((await counter.get()).data()?.count === 12, 'Failed transaction rolls back');
await counter.update({ timestamp: FieldValue.serverTimestamp(), removable: 'x' });
await counter.update({ removable: FieldValue.delete(), count: FieldValue.increment(2) });
check((await counter.get()).data()?.timestamp.toDate() instanceof Date, 'Timestamp shape preserved');
check((await counter.get()).data()?.count === 14 && !('removable' in (await counter.get()).data()!), 'Increment and deletion preserve legacy semantics');
await db.collection('patients').doc('p1').set({ name: 'Example', email: 'example@test.invalid', homeBranchId: 'b1' });
await db.collection('patients').doc('p2').set({ name: 'Second', homeBranchId: 'b2' });
check((await db.collection('patients').where('homeBranchId', 'in', ['b1']).get()).size === 1, 'IN query supported');
check((await db.collection('patients').where('name', '>=', 'Example').where('name', '<', 'Example\uf8ff').get()).size === 1, 'Range query supported');
await assert.rejects(db.collection('patients').where("name'); DROP TABLE app_records;--", '==', 'x').get()); assertions++;
await db.collection('branches').doc('b1').set({ branchName: 'One', status: 'Active' });
await db.collection('branches').doc('b2').set({ branchName: 'Two', status: 'Active' });
await db.collection('inventory_items').doc('item1').set({ name: 'Cream', sku: 'CREAM', lowStockThreshold: 1 });
await db.collection('inventory_stocks').doc('stock1').set({ itemId: 'item1', branchId: 'b1', quantity: 10 });

const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
const port = (server.address() as any).port; const origin = new URL(process.env.APP_URL || 'http://localhost:3000').origin;
const secure = origin.startsWith('https://');
const tokens: Record<string, { cookie: string; csrf: string }> = {};
for (const role of ['admin', 'staff', 'doctor', 'pending', 'support_developer']) {
  const id = `test-${role}`; const token = Buffer.alloc(32, Object.keys(tokens).length + 1).toString('base64url'); const csrf = `csrf-${role}`;
  await db.collection('users').doc(id).set({ role: role === 'pending' ? 'staff' : role, fullName: role, email: `${role}@test.invalid`, active: role !== 'pending', assignedBranches: ['b1'] });
  await pool.query('INSERT INTO auth_identities (google_subject, user_id, email) VALUES ($1, $2, $3)', [id, id, `${role}@test.invalid`]);
  await pool.query("INSERT INTO auth_sessions (token_hash,user_id,csrf_token,expires_at) VALUES ($1,$2,$3,now()+interval '1 hour')", [createHash('sha256').update(token).digest('hex'), id, csrf]);
  tokens[role] = { cookie: `${secure ? '__Host-vine_session' : 'vine_session'}=${token}`, csrf };
}
async function post(endpoint: string, body: any, role?: string, extra?: Record<string, string>) {
  const token = role ? tokens[role] : undefined;
  return fetch(`http://127.0.0.1:${port}${endpoint}`, { method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/json', ...(token ? { Cookie: token.cookie, Authorization: `Bearer ${token.csrf}` } : {}), ...extra }, body: JSON.stringify(body) });
}
try {
  check((await post('/api/data/query', { kind: 'document', path: 'settings/branding' })).ok, 'Branding publicly readable');
  check((await post('/api/data/query', { kind: 'collection', path: 'patients' })).status === 401, 'Anonymous clinical reads rejected');
  check((await post('/api/data/query', { kind: 'document', path: 'users/test-pending' }, 'pending')).ok, 'Pending account can read own activation state');
  check((await post('/api/data/query', { kind: 'collection', path: 'patients' }, 'pending')).status === 403, 'Pending clinical reads rejected');
  check((await post('/api/data/query', { kind: 'collection', path: 'patients' }, 'staff')).ok, 'Approved staff can read shared patient directory');
  check((await post('/api/data/query', { kind: 'collection', path: 'audit_logs' }, 'staff')).status === 403, 'Audit access restricted');
  check((await post('/api/data/query', { kind: 'collection', path: 'patients/p1/privateNotes' }, 'staff')).status === 403, 'Private note reads restricted');
  check((await post('/api/data/query', { kind: 'collection', path: 'patients' }, 'staff', { Origin: 'https://evil.invalid' })).status === 403, 'Cross-origin requests rejected');
  check((await post('/api/data/write', { operations: [{ path: 'users/test-staff', mode: 'update', data: { role: 'admin' } }] }, 'staff')).status === 403, 'Self privilege escalation rejected');
  check((await post('/api/data/write', { operations: [{ path: 'users/test-staff', mode: 'update', data: { fullName: 'Updated', lastUpdatedBy: 'test-staff' } }] }, 'staff')).ok, 'Allowed self profile fields update');
  check((await post('/api/data/write', { operations: [{ path: 'patients/p1', mode: 'update', data: { name: 'Overwrite' } }] }, 'admin')).status === 403, 'Clinical mutations cannot bypass dedicated validation');
  check((await post('/api/data/write', { operations: [{ path: 'users/test-staff', mode: 'update', data: { active: false } }] }, 'admin')).status === 403, 'Account lifecycle cannot bypass dedicated endpoint');
  check((await post('/api/data/write', { operations: [{ path: 'branches/b1', mode: 'delete' }] }, 'admin')).status === 403, 'Linked branch cannot be deleted');
  check((await post('/api/data/write', { operations: [{ path: 'settings/branding', mode: 'set', merge: true, data: { maintenanceMode: true } }] }, 'admin')).status === 403, 'Maintenance requires dedicated support endpoint');
  const patientPayload = { name: 'Migration Patient', email: 'migration@test.invalid', contactNumber: '+639171234567', gender: 'Female', address: 'Test address', mainConcern: 'Consultation', birthday: '1990-01-01', homeBranchId: 'b1', status: 'Active' };
  const createdPatient = await post('/api/records/patients', patientPayload, 'doctor');
  check(createdPatient.status === 201, 'Patient registration works through migrated backend');
  const patientRecord = await createdPatient.json();
  check(typeof patientRecord.patientID === 'string', 'Patient identifier generated');
  check((await post('/api/records/patients', patientPayload, 'doctor')).status === 409, 'Duplicate patient rejected');
  const appointmentPayload = { patientId: patientRecord.id, branchId: 'b1', doctorId: 'test-doctor', appointmentDate: '2030-01-01T10:00', visitType: 'Initial Consultation', status: 'Arrived', mainConcern: 'Consultation', notes: 'Test notes' };
  const booking = await post('/api/records/appointments', appointmentPayload, 'doctor');
  check(booking.status === 201, 'Appointment registration works'); const appointmentRecord = await booking.json();
  check((await post('/api/records/appointments', appointmentPayload, 'doctor')).status === 409, 'Doctor double booking rejected');
  const visitPayload = { patientId: patientRecord.id, branchId: 'b1', doctorId: 'test-doctor', visitDate: '2030-01-01T10:00', appointmentId: appointmentRecord.id, visitType: 'Initial Consultation', mainConcern: 'Consultation', notes: 'Clinical note', diagnosis: 'Test assessment', treatmentPlan: 'Test plan', visitOutcome: 'Completed' };
  const encounter = await post('/api/records/visits', visitPayload, 'doctor');
  check(encounter.status === 201, 'Linked visit registration works'); const visitRecord = await encounter.json();
  check((await db.collection('appointments').doc(appointmentRecord.id).get()).data()?.visitHistoryCreated === true, 'Appointment linked to visit atomically');
  check((await db.collection('patients').doc(patientRecord.id).get()).data()?.totalVisits === 1, 'Patient visit summary updated');
  check((await post('/api/records/visits', visitPayload, 'doctor')).status === 409, 'Duplicate linked visit rejected');
  const form = new FormData(); form.append('file', new Blob(['%PDF-1.4\nTest attachment'], { type: 'application/pdf' }), 'test.pdf');
  form.append('patientId', patientRecord.id); form.append('resourceType', 'visit'); form.append('resourceId', visitRecord.id); form.append('note', 'Test attachment');
  const upload = await fetch(`http://127.0.0.1:${port}/api/attachments/upload`, { method: 'POST', headers: { Origin: origin, Cookie: tokens.doctor.cookie, Authorization: `Bearer ${tokens.doctor.csrf}` }, body: form });
  check(upload.status === 201, 'Private attachment uploaded to local storage');
  const uploaded = await upload.json(); const storagePath = uploaded.attachment.storagePath;
  const downloadPath = `/api/attachments/content?path=${encodeURIComponent(storagePath)}`;
  check((await fetch(`http://127.0.0.1:${port}${downloadPath}`)).status === 401, 'Anonymous attachment download rejected');
  const download = await fetch(`http://127.0.0.1:${port}${downloadPath}`, { headers: { Cookie: tokens.doctor.cookie, Authorization: `Bearer ${tokens.doctor.csrf}` } });
  check(download.ok && (await download.text()).startsWith('%PDF'), 'Authenticated attachment content returned');
  const removal = await fetch(`http://127.0.0.1:${port}/api/attachments`, { method: 'DELETE', headers: { Origin: origin, Cookie: tokens.doctor.cookie, Authorization: `Bearer ${tokens.doctor.csrf}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ storagePath }) });
  check(removal.status === 204, 'Attachment deletion updates metadata and local storage');
  const archive = await fetch(`http://127.0.0.1:${port}/api/records/visits/${visitRecord.id}`, { method: 'DELETE', headers: { Origin: origin, Cookie: tokens.admin.cookie, Authorization: `Bearer ${tokens.admin.csrf}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ reason: 'Test archive' }) });
  check(archive.ok, 'Visit archived');
  check((await post(`/api/records/visits/${visitRecord.id}/restore`, {}, 'admin')).ok, 'Visit restored');
  const transfer = await post('/api/inventory/transfers/create', { itemId: 'item1', fromBranchId: 'b1', toBranchId: 'b2', quantity: 3 }, 'admin'); check(transfer.ok, 'Valid transfer created');
  const { id } = await transfer.json();
  const completions = await Promise.all([post('/api/inventory/transfers/complete', { id }, 'admin'), post('/api/inventory/transfers/complete', { id }, 'admin')]);
  check(completions.every(response => response.ok), 'Transfer completion safely retries');
  check((await db.collection('inventory_stocks').doc('stock1').get()).data()?.quantity === 7, 'Transfer deducts source once');
  const destination = await db.collection('inventory_stocks').where('branchId', '==', 'b2').get();
  check(destination.docs[0].data()?.quantity === 3, 'Transfer adds destination once');
  check((await post('/api/inventory/transfers/create', { itemId: 'item1', fromBranchId: 'b1', toBranchId: 'b2', quantity: -1 }, 'admin')).status === 400, 'Negative stock movement rejected');
  check((await post('/api/inventory/transfers/create', { itemId: 'item1', fromBranchId: 'b1', toBranchId: 'b2', quantity: 99 }, 'admin')).status === 400, 'Overselling stock rejected');
  const health = await fetch(`http://127.0.0.1:${port}/api/health`);
  check(health.ok && health.headers.get('x-content-type-options') === 'nosniff', 'Health endpoint has security headers');
  check(!health.headers.has('x-powered-by'), 'Framework fingerprint suppressed');
  check((await fetch(`http://127.0.0.1:${port}/api/not-a-real-endpoint`)).status === 404, 'Unknown API does not serve HTML');
  const invalidJson = await fetch(`http://127.0.0.1:${port}/api/data/query`, { method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/json' }, body: '{bad' });
  check(invalidJson.status === 400 && invalidJson.headers.get('content-type')?.includes('application/json'), 'Malformed request returns safe JSON error');
  const unauthorizedUpload = new FormData(); unauthorizedUpload.append('file', new Blob(['test']), 'test.pdf');
  check((await fetch(`http://127.0.0.1:${port}/api/attachments/upload`, { method: 'POST', body: unauthorizedUpload })).status === 401, 'Upload authentication runs before multipart processing');
  check((await post('/api/developer/maintenance', { maintenanceMode: true }, 'support_developer')).ok, 'Support can enable write maintenance');
  check((await post('/api/records/patients', { ...patientPayload, email: 'blocked@test.invalid' }, 'doctor')).status === 503, 'Maintenance blocks clinical mutations on server');
  check((await post('/api/data/query', { kind: 'document', path: 'settings/branding' })).ok, 'Maintenance preserves public settings reads');
  check((await post('/api/developer/maintenance', { maintenanceMode: false }, 'support_developer')).ok, 'Support can end maintenance');
  check((await post('/api/auth/logout', {}, 'staff')).ok, 'Logout revokes session');
  check((await post('/api/data/query', { kind: 'collection', path: 'patients' }, 'staff')).status === 401, 'Revoked session cannot read records');
  check((await fetch(`http://127.0.0.1:${port}/api/auth/google/callback?state=forged&code=forged`, { redirect: 'manual' })).headers.get('location')?.includes('auth_error'), 'Forged OAuth callback rejected');
  console.log(`Passed ${assertions} PostgreSQL, authorization, session and inventory checks.`);
} finally { server.close(); await pool.end(); }
