import assert from 'node:assert/strict';
import { patientDuplicateReasons, possiblePatientDuplicates } from '../src/utils/patientDuplicates';
let checks=0;
const check=(fn:()=>void)=>{fn();checks++;};
const existing={id:'p1',patientID:'QA-1',name:'Ana Santos',contactNumber:'09171234567',email:'ana@example.invalid',birthday:'1990-01-01'};
for(const phone of ['09171234567','+63 917 123 4567','9171234567','00639171234567']) check(()=>assert.ok(patientDuplicateReasons({contactNumber:phone},existing).includes('Same mobile number')));
for(const phone of ['0917','917','', '12345']) check(()=>assert.equal(patientDuplicateReasons({contactNumber:phone},existing).length,0));
check(()=>assert.ok(patientDuplicateReasons({name:' ANA  SANTOS '},existing).includes('Same full name')));
check(()=>assert.ok(patientDuplicateReasons({email:' ANA@EXAMPLE.INVALID '},existing).includes('Same email address')));
check(()=>assert.equal(patientDuplicateReasons({name:'Ana Santosa'},existing).length,0));
check(()=>assert.equal(patientDuplicateReasons({birthday:'1990-01-01'},existing).length,0));
for(const birthDateStatus of ['unknown','estimated_age','estimated_year'])check(()=>assert.ok(!patientDuplicateReasons({name:'Ana Santos',birthday:'1990-01-01',birthDateStatus},existing).some(r=>r.includes('date of birth'))));
check(()=>assert.ok(patientDuplicateReasons({name:'Ana Santos',birthday:'1990-01-01',birthDateStatus:'exact'},existing).includes('Same full name and exact date of birth')));
check(()=>assert.ok(!patientDuplicateReasons({name:'Ana Santos',birthday:'1995-01-01'},existing).some(r=>r.includes('date of birth'))));
check(()=>assert.equal(patientDuplicateReasons({},{}).length,0));
check(()=>assert.equal(patientDuplicateReasons({email:'bad'},{email:'bad'}).length,0));
check(()=>assert.equal(possiblePatientDuplicates({id:'p1',name:'Ana Santos'},[existing]).length,0));
const records=[existing,{...existing,id:'p2',patientID:'QA-2',isArchived:true},{...existing,id:'p3',patientID:'QA-3',status:'Inactive'}];
check(()=>assert.equal(possiblePatientDuplicates({name:'Ana Santos'},records).length,3));
check(()=>assert.deepEqual(possiblePatientDuplicates({name:'Ana Santos'},records).map(m=>m.patient.patientID),['QA-1','QA-2','QA-3']));
const before=JSON.stringify(records);possiblePatientDuplicates({name:'Ana Santos'},records);check(()=>assert.equal(JSON.stringify(records),before));
check(()=>assert.equal(possiblePatientDuplicates({name:'Someone Else',contactNumber:'09171234567'},records).length,3));
console.log(`${checks} advisory patient duplicate checks passed (pure matching, not browser acceptance).`);
